config/routes.rb
Rails.application.routes.draw do
  root "sessions#index"

  resources :users do
    resources :tasks do
      resources :workers
    end
  end

  
  
  resources :sessions, only: [:new,:index, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :workers,dependent: :destroy

  validates :description, presence: true, length: { minimum: 4, maximum: 254 }
  validates :amount , presence: true,format: {with: /\A[+-]?\d+(\.[\d]+)?\z/  , message: "Amount invalid"}
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :tasks,dependent: :destroy

    def welcome
        "Hello, #{self.email}!"
    end

    validates :name ,:mobileno,:address,:city,:pincode,:state,:email,:password, presence: true,on: :create
    validates :email , format: { with: /\A(\S+)@(.+)\.(\S+)\z/, message: "Email invalid"  },
    uniqueness: { case_sensitive: false },
    length: { minimum: 4, maximum: 254 },on: :create
    validates :address,length: { minimum: 4, maximum: 254 },on: :create
end

app/models/worker.rb
class Worker < ApplicationRecord
    belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login
    helper_method :current_user

    def require_login
        redirect_to new_session_path unless session.include? :user_id
    end
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :require_login, only: [:create, :new]
  def index
    @tasks = Task.all
  end

  def new
  end

  def create
    session_params = params.permit(:email,:password)
    @user = User.find_by(email: session_params[:email])

    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:notice] = "Login is invalid!"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been signed out!"
    redirect_to new_session_path
  end

  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


    def create
        @user = User.find(params[:user_id])
        @task = @user.tasks.create(task_params)
        redirect_to user_path(@user)
    end
    
    def new
        @task = Task.new
    end

    def destroy
        @user = User.find(params[:user_id])

        @task = @user.tasks.find(params[:id])
        
        @task.destroy
        
        redirect_to user_path(@user), status: :see_other
    end

    def edit
        @user = User.find(params[:user_id])
        @task = @user.tasks.find(params[:id])   
        render :edit  
    end

    def update
        @user = User.find(params[:user_id])
        @task = @user.tasks.find(params[:id])
        if @task.update(task_params)
            flash[:success] = "task updated successfully"
            redirect_to @user
          else
            flash.now[:error] = "task could not be updated"
            render :edit
          end

        
    end
    private
    def task_params
        params.require(:task).permit!
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    skip_before_action :require_login, only: [:new, :create]

    def show
      $count =1
      @user = User.find(params[:id])
    end

    def index
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.create(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to new_session_path
      else
        
        flash[:error] = "Error- please try to create an account again."
        render :new, status: :unprocessable_entity
      end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])

        if @user.update(user_params)
            flash[:notice] = "Updating Profile Sucessfully"
            redirect_to @user
        else
            # redirect_to edit_user_path
            redirect_to :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy

        redirect_to new_session_path, status: :see_other
    end
  
    private 

    def user_params
      params.require(:user).permit(:email, :password,:name,:mobileno,:state,:pincode,:city,:address)
    end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
    def new 
        @worker = Worker.new
    end

    def create
        byebug
        @user = User.find(params[:user_id])
        @task = Task.find(params[:task_id])
        @worker = @task.workers.create(worker_params)
        if @worker.save
            flash[:notice]= "Task Alloted Successfully"
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end


    private

    def worker_params
        params.require(:worker).permit(:name,:email,:address,:age,:mobileno)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeService</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <style>
    table,
    th,
    td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    /* setting the text-align property to center*/
    td,th {
        padding: 5px;
        text-align: center;
    }
</style>
  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="text-center">
    <%= form_with model: [ @user, @user.tasks.build ] do |form| %>
      <div class="row">
      <div class="col-md-3">
        <div class="mb-2 row">
        <%= form.label :category ,{for:"floatingSelectGrid",class:"form-label"}%><br>
        <%= form.select :category ,["plumber","electrician"],{class:"form-control form-control-lg" ,id:"floatingSelectGrid" }%> 
        </div>
      </div>
      <div class="col-md-3">
        <div class="mb-2 row">
        <%= form.label :status ,{for:"floatingSelectGrid",class:"form-label"}%><br>
        <%= form.select :status,["ACTIVE","DEACTIVE"],{class:"form-control form-control-lg" ,id:"floatingSelectGrid" }%>
        </div>
      </div>
      <div class="col-md-3">
        <div class="mb-2 row">
        <%= form.label :description ,{for:"exampleFormControlTextarea1" ,class:"form-label"}%><br>
        <%= form.text_area :description, {class:"form-control" ,id:"exampleFormControlTextarea1" }%>
        </div>
      </div>
      <div class="col-md-3">
        <div class="mb-2 row">
        <%= form.label :amount,{class:"form-label"} %><br>
        <%= form.text_field :amount %><br>
        
        </div>
      </div>
        <%= form.submit %><br>
      </div>  
      
    <% end %><br>
</div>

app/views/tasks/_task.html.erb
<% if task.status == "ACTIVE"%>


<tr  class="text-dark bg-success">
  <th scope="row">
  <p>
      <%= $count %>
    </p>
    </th>
    <td>
    <p>
      <%= task.category %>
    </p>
  </td> 
  <td>
    <p>
      
      <%= task.description %>
    </p>
  </td> 
  <td> 
     <p>
      <%= task.amount %>/-
     </p>
  </td>
  <td> 
     <p>
      <%= task.status %>
     </p>
  </td>
  <td> 
   <p>
    <%= task.created_at.strftime("%H:%M:%S") %>
   </p>
</td>
<td> 
<p>
 <%= task.updated_at.strftime("%H:%M:%S") %>
</p>
</td>
  <td>
  <p><%= link_to "Edit Profile" , edit_user_task_path(@user,task), class: 'btn btn-outline-dark btn-sm'%>
    <%= link_to "Delete Task", [task.user, task], data: 
    {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } , class: 'btn btn-outline-dark btn-sm'%>
  </p>
  </td>
 </tr>
 <% $count = $count + 1 %>
  
<% elsif task.status == "DEACTIVE"%>
<tr class="text-dark bg-danger">
<th scope="row">
<p>
    <%= $count %>
  </p>
  </th>
  <td>
  <p>
    <%= task.category %>
  </p>
</td> 
<td>
  <p>
    
    <%= task.description %>
  </p>
</td> 
<td> 
   <p>
    <%= task.amount %>/-
   </p>
</td>
<td> 
   <p>
    <%= task.status %>
   </p>
</td>
<td> 
   <p>
    <%= task.created_at.strftime("%H:%M:%S") %>
   </p>
</td>
<td> 
<p>
 <%= task.updated_at.strftime("%H:%M:%S") %>
</p>
</td>
<td>
<p><%= link_to "Edit Profile" , edit_user_task_path(@user,task), class: 'btn btn-outline-dark btn-sm'%>
  <%= link_to "Delete Task", [task.user, task], data: 
  {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } , class: 'btn btn-outline-dark btn-sm'%>
</p>
</td>
</tr>
<% $count = $count+1 %>
<%end%>

app/views/tasks/edit.html.erb
<div>
<h1>Edit Tak</h1>

<%= form_with model: @task, method: :patch, url: user_task_path(@user, @task), local: true do |form| %>    <p>
    <div class="row">
    <div class="col-md-3">
      <div class="mb-2 row">
      <%= form.label :category ,{for:"floatingSelectGrid",class:"form-label"}%><br>
      <%= form.select :category ,["plumber","electrician"],{class:"form-control form-control-lg" ,id:"floatingSelectGrid" }%>
      </div>
    </div>
    <div class="col-md-3">
      <div class="mb-2 row">
      <%= form.label :status ,{for:"floatingSelectGrid",class:"form-label"}%><br>
      <%= form.select :status,["ACTIVE","DEACTIVE"],{class:"form-control form-control-lg" ,id:"floatingSelectGrid" }%>
      </div>
    </div>
    <div class="col-md-3">
      <div class="mb-2 row">
      <%= form.label :description ,{for:"exampleFormControlTextarea1" ,class:"form-label"}%><br>
      <%= form.text_area :description, {class:"form-control" ,id:"exampleFormControlTextarea1" }%>
      </div>
    </div>
    <div class="col-md-3">
      <div class="mb-2 row">
      <%= form.label :amount,{class:"form-label"} %><br>
      <%= form.text_field :amount %><br>
      </div>
    </div>
      <%= form.submit %><br>
    </div>  
  <% end %>

</div>

app/views/tasks/new.html.erb
<%= render "form"%>

app/views/tasks/show.html.erb
<h1>hiii</h1>

app/views/users/_form.html.erb
<%= form_with model: @user do |f| %>
  <div class="mb-3 row">
    <%= f.label :name,{class:"col col-form-label"}%>
    <div class="col-sm-10">
    <%= f.text_field :name ,{class:"form-control form-control-lg"}%>
    </div>
  </div>
    
    <% @user.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
    <% end %>
    <hr>
    <div class="mb-3 row">
    <%= f.label :mobile_no,{class:"col col-form-label"} %>
    <div class="col-sm-10">
    <%= f.text_field :mobileno ,{class:"form-control form-control-lg"}%>
    </div>
  </div>
    
    <% @user.errors.full_messages_for(:mobileno).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <hr>
    <div class="mb-3 row">
    <%= f.label :address,{class:"col col-form-label"} %>
    <div class="col-sm-10">
    <%= f.text_area :address,{class:"form-control form-control-lg"} %>
    </div>
  </div>
    
    <% @user.errors.full_messages_for(:address).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <hr>
    <div class="mb-3 row">
    <%= f.label :city,{class:"col col-form-label"} %>
    <div class="col-sm-10">
    <%= f.text_field :city ,{class:"form-control form-control-lg"}%>
    </div>
  </div>
    
    <% @user.errors.full_messages_for(:city).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <hr>
    <div class="mb-3 row">
    <%= f.label :pincode,{class:"col col-form-label"} %>
    <div class="col-sm-10">
    <%= f.text_field :pincode,{class:"form-control form-control-lg"} %>
    </div>
  </div>
    
    <% @user.errors.full_messages_for(:pincode).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <hr>
    <div class="mb-3 row">
    <%= f.label :state,{class:"col col-form-label"} %>
    <div class="col-sm-10">
    <%= f.text_field :state ,{class:"form-control form-control-lg"}%>
    </div>
  </div>
    
    <% @user.errors.full_messages_for(:state).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <hr>
    <div class="mb-3 row">
    <%= f.label :email,{class:"col col-form-label"} %>
    <div class="col-sm-10">
    <%= f.text_field :email ,{class:"form-control form-control-lg"}%>
    </div>
  </div>
    
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <hr>
    <% if @user.id?%>
    <div class="mb-3 row">
    <%= f.label :new_password,{class:"col col-form-label"} %>
    <div class="col-sm-9">
    <%= f.password_field :password ,{class:"form-control form-control-lg"}%>
    </div>
  </div>
  <%else%>
  <div class="mb-3 row">
  <%= f.label :password,{class:"col col-form-label"} %>
  <div class="col-sm-9">
  <%= f.password_field :password ,{class:"form-control form-control-lg"}%>
  </div>
</div>
  <%end%>
    
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <hr>
    <div class="mb-3 row">
    <%= f.submit "Submit!!"%><hr>
    </div>
<% end %>

app/views/users/edit.html.erb
<div class="container border bg-info" style="width:500px;text-align:center">
<br>
<%= render "form"%>
</div>

app/views/users/new.html.erb
<div class="container border bg-info" style="width:500px;text-align:center">

<% if flash[:error] %>
  <%= content_tag :h1, flash[:error], {style:"color:red"} %>
<% else %>
<%= content_tag :h1, "Create Account", {style:"color:green"} %>
<% end %>

<%= render "form" %>
</div>

app/views/users/show.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    
      <img src="https://media.istockphoto.com/id/515708494/photo/mahatma-gandhi-hall.jpg?s=612x612&w=0&k=20&c=0r0tu3VAbZdmf4RlwI3Q-xZjiMa4abSfsvnDxHVlGCo=" alt="no image found" width="100" height="50" class="d-inline-block align-text-center">
      <i><b>Admin Portal</b></i>
    
    <h1>Hiii,  <%= @user.name %></h1>
  </div>
</nav>

<div style="float:right">
<%= link_to "Logout" ,root_path ,{class:"btn btn-danger"}%>&nbsp;&nbsp;&nbsp;&nbsp;
<%= link_to "Edit Profile" , edit_user_path ,{class:"btn btn-info"}%>
</div><br>
<h2>Add a new Tasks : </h2>
<%= render "tasks/form" %>


<h2>Previously Added Tasks : </h2>
<table class="table table-hover table-bordered border-dark" >
<thead class="table-info">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Category</th>
      <th scope="col">Description</th>
      <th scope="col">Amount</th>
      <th scope="col">Status</th>
      <th scope="col">Created At</th>
      <th scope="col">Edited At</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render @user.tasks %>
    <% $count = 1 %>
  </tbody>
</table>


    

app/views/workers/new.html.erb
<div class="container">
    <h1>Please Sign up to register the task to your name .....</h1>

        <%= form_with model: [:user, :task, @worker]  do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %><br>
            <%= f.label :mobileno %>
            <%= f.text_field :mobileno %><br>
            <%= f.label :address %>
            <%= f.text_area :address %><br>
            <%= f.label :email %>
            <%= f.text_field :email %><br>
            <%= f.label :age %>
            <%= f.text_field :age %><br>
            
            <%= f.submit "Submit!!"%>
        <% end %>
</div>